name: tta_ft
channels:
  - pytorch
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/main/
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - readline=8.1=h27cfd23_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
      - accelerate==0.16.0
      - addict==2.4.0
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - appdirs==1.4.4
      - attr==0.3.1
      - attrs==21.2.0
      - autoattack==0.1
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - black==19.3b0
      - braceexpand==0.1.7
      - cffi==1.16.0
      - chardet==3.0.4
      - charset-normalizer==3.3.0
      - click==8.0.3
      - cloudpickle==2.0.0
      - contourpy==1.1.0
      - crcmod==1.7
      - cryptography==41.0.4
      - cycler==0.11.0
      - decorator==5.1.0
      - diffusers==0.16.0
      - docker-pycreds==0.4.0
      - einops==0.4.1
      - filelock==3.12.2
      - flake8==4.0.1
      - fonttools==4.42.0
      - fsspec==2023.6.0
      - ftfy==6.3.1
      - fvcore==0.1.6
      - gdown==5.1.0
      - geotorch==0.3.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - googledrivedownloader==0.4
      - grad-cam==1.5.5
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==2.10
      - imagecorruptions==1.1.2
      - imageio==2.10.1
      - importlib-metadata==8.6.1
      - inquirerpy==0.3.4
      - iopath==0.1.9
      - ipython==7.28.0
      - isort==4.3.21
      - jedi==0.18.0
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.1.0
      - kiwisolver==1.4.4
      - kornia==0.6.8
      - markdown-it-py==3.0.0
      - markupsafe==2.0.1
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.3
      - mccabe==0.6.1
      - mdurl==0.1.2
      - mmengine==0.10.7
      - mpmath==1.3.0
      - networkx==2.6.3
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - open-clip-torch==2.31.0
      - opencv-python==4.8.0.76
      - oss2==2.17.0
      - packaging==21.0
      - pandas==2.2.3
      - parameterized==0.8.1
      - parso==0.8.2
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pfzy==0.3.4
      - pickleshare==0.7.5
      - pillow==9.4.0
      - portalocker==2.3.2
      - promise==2.3
      - prompt-toolkit==3.0.21
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pyautoattack==0.2.0
      - pycodestyle==2.8.0
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pyflakes==2.4.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytorchcv==0.0.67
      - pytz==2023.3.post1
      - pywavelets==1.1.1
      - pyyaml==6.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.4.2
      - robustbench==1.1
      - safetensors==0.5.3
      - scikit-image==0.18.3
      - scikit-learn==1.0.1
      - scipy==1.9.3
      - seaborn==0.12.2
      - sentry-sdk==1.9.0
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - shortuuid==1.0.11
      - simplejson==3.17.5
      - smmap==5.0.0
      - soupsieve==2.6
      - submitit==1.4.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.3.0
      - threadpoolctl==3.0.0
      - tifffile==2021.10.12
      - timm==1.0.9
      - tokenizers==0.13.3
      - toml==0.10.2
      - torch==2.1.0+cu121
      - torchdiffeq==0.2.5
      - torchvision==0.16.0+cu121
      - tqdm==4.56.2
      - traitlets==5.1.0
      - transformers==4.26.0
      - triton==2.1.0
      - ttach==0.0.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==1.25.11
      - wandb==0.12.17
      - wcwidth==0.2.5
      - webdataset==0.2.86
      - yacs==0.1.8
      - yapf==0.31.0
      - yattag==1.14.0
      - zipp==3.21.0
